#
# https://www.npmjs.com/package/serverless
# https://blog.logrocket.com/going-serverless-node-js-apps/
#
service: npm-serverless-template
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
functions:
  productAPI:
    handler: Controller/products.handler
    events:
      - http:
          path: /index
          method: get
      - http:
          path: /
          method: post
      - http:
          path: /
          method: get
      - http:
          path: /{productId}
          method: get
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
